### ISSUE TITLE
Experiencia en el sitio con errores

### ISSUE THREAD

**Issue by alelazcano** [mobbexco/prestashop#10]
Hola, buen día.
Reportamos de varios clientes en la versión 2.0.1 y 2.0.2 que la "experiencia en el sitio" (sin salir al checkout de mobbex) presenta errores de consola por CORS y no carga la misma.

![](https://snipboard.io/JEXLZb.jpg)

El sitio cuenta con SSL, se descartaron problemas de la plantilla, etc.

Al desactivarse la opción, la salida desde la web a mobbex se hace sin problemas y se puede cerrar el circuito de compra.

Saludos.

**Comment by jlmobbex** [comment]
Hola!

**Comment by jlmobbex** [comment]
Hola! Podría ser que su configuración del archivo htaccess esté bloqueando la entrada.
Puede intentar solucionarlo incluyendo el dominio en la lista de dominios permitidos al final del archivo .htaccess, ubicado en la carpeta de instalación de prestashop. El código a incluír sería el siguiente:
`<IfModule mod_headers.c>`
`    Header set Access-Control-Allow-Origin https://api.mobbex.com`
`</IfModule>`
Saludos!
