### ISSUE TITLE
Planes "ahora" poco funcionales en algunos casos

### ISSUE THREAD

**Issue by alelazcano** [mobbexco/prestashop#11]
Buen día.

Por reporte de algunos clientes, se les hace difícil poder gestionarse bien con los planes "ahora" (12, 18, etc); ya por otras vías contacté y añadieron la funcionalidad de seleccionar cuales productos "NO" deben presentar estos planes, ya que por norma de Comercio o decisión comercial propia no se quiera en tal artículo o rubro ofrecer. Se agradece la pronta predisposición de haber añadido la funcionalidad.

El inconveniente surge ahora en que por defecto "todos" los productos tienen activo "ahora", salvo se tilde que NO deben cargarlo; en algunos comercios se quiere hacer esta operatoria y, de forma masiva por base de datos, se puede armar una consulta. Es poco práctico, de todas formas, ya que cuando se agregan productos nuevos hay que reconfigurar esos mismos.

En el rubro tecnología, además, por política de cada empresa, suele darse que quieren solo ofrecer "ahora 3 y ahora 6" y no más cuotas.

La solicitud o sugerencia, más bien, es que se considere esto para facilitar o bien "no operar conplanes ahora" y seleccionar cuales si van a tener o alguna otra funcionalidad que a vistas del comercio agilice la operatoria a futuro.

Es feedback de clientes.

Gracias por la predisposiciòn de siempre, saludos.

**Comment by jlmobbex** [comment]
Gracias por el comentario @alelazcano!

**Comment by jlmobbex** [comment]
Gracias por el comentario @alelazcano! Ahora mismo estamos trabajando en nuevas características relacionadas a la aplicación de filtros, para que sea más sencillo aplicarlos o deactivarlos en conjunto. Posiblemente estén listas para la próxima versión!
Saludos!
