### ISSUE TITLE
Compile Error: require_once(): Failed opening required

### ISSUE THREAD

**Issue by santiagobrito** [mobbexco/prestashop#141]
Hola, al instalarlo en Prestashop tengo este error

```
Compile Error: require_once(): Failed opening required '/home/pruebas/public_html/ps7/modules/mobbex/vendor/autoload.php' (include_path='/home/pruebas/public_html/ps7/vendor/pear/pear_exception:/home/pruebas/public_html/ps7/vendor/pear/console_getopt:/home/pruebas/public_html/ps7/vendor/pear/pear-core-minimal/src:/home/pruebas/public_html/ps7/vendor/pear/archive_tar:.:/opt/cpanel/ea-php73/root/usr/share/pear')

[Symfony\Component\Debug\Exception\FatalErrorException 0]
```

Probado con PHP7.3 Y PHP7.4. Versión de Prestashop: 1.7.8.7

**Comment by jlmobbex** [comment]
Hola @santiagobrito! El error probablemente se deba a que el `build` que están usando se encuentra incompleto, te recuerdo que el archivo `build.sh` está destinado únicamente al desarrollo del módulo, y que la instalación del plugin debe hacerse [según se especifica en el readme](https://github.com/mobbexco/prestashop#instalaci%C3%B3n).
Avisame si instalando el asset (mobbex.3.3.0.ps-1.6-1.7.zip) se soluciona el problema. Gracias!
