### ISSUE TITLE
El hook ActionEmailSendBefore no se registra.

### ISSUE THREAD

**Issue by mescalitog** [mobbexco/prestashop#163]
El hook ActionEmailSendBefore, que deberia impedir que se envien emails de confirmacion al crear una orden iniciando el checkout parece que no se registra y por lo tanto se envia un email de confirmacion.

**Comment by jlmobbex** [comment]
Hola @mescalitog! Gracias por la información, ya estamos revisando el inconveniente para que quede corregido a la brevedad.
