### ISSUE TITLE
Problema en Prestashop 1.7.6.9

### ISSUE THREAD

**Issue by matiascorrea** [mobbexco/prestashop#179]
Hola, hace varios días vengo intentando intentando hacer funcionar el modulo pero no puedo.

Versión PHP: 7.2.34
Versión de PrestaShop: 1.7.6.9

Tenia una versión vieja del plugin (desactivada) que había usado hace un tiempo. La desinstale.
Instale la nueva versión. Me dio error. Luego intente instalar de nuevo y termino OK.
Puedo entrar a la configuración y configurar todo OK.

El problema:
- En el front no aparece nada del modulo, ni en la pagina del producto, ni en el checkout.
- Si pongo el modo debug me muestra este error en el front (adjunto imagen).
- En Diseño - Posiciones, no veo ningún hook de mobbek.
- Revise la tabla PS_hook y no hay ninguno de mobbex

Estoy usando la ultima versión que la baje desde acá https://github.com/mobbexco/prestashop/releases

![error mobbex](https://user-images.githubusercontent.com/19633679/232216675-51f92890-6f08-4589-9486-8470d6825e77.PNG)

Agradecería si me pueden ayudar.

Gracias

**Comment by jlmobbex** [comment]
Buen día @matiascorrea! Gracias por tu comentario. Te pido si podés probar desinstalando y reinstalando el plugin mediante el archivo [mobbex.3.5.2.ps-1.6-1.7.zip](https://github.com/mobbexco/prestashop/releases/download/3.5.2/mobbex.3.5.2.ps-1.6-1.7.zip) que se encuentra en la última release. El error que se muestra no parece relacionarse con Mobbex debido a que dentro del módulo no se hace uso de la posición `quantity`, pero los hooks deberían registrarse al instalar.

**Comment by jlmobbex** [comment]
Perfecto lo del template! En cuanto al nuevo inconveniente, antes de reinstalar te pido si podés buscar el mensaje de log completo (debería estar alojado en base de datos, en la tabla `ps_log`).

**Comment by matiascorrea** [comment]
El log es este:
Mobbex fatal: Observer > hookDisplayBackOfficeHeader | Error Obtaining Update/Upgrade Messages \"Error getting latest release data #SSL certificate problem: unable to get local issuer certificate\"

Lo estoy probando en local.

Saludos

**Comment by jlmobbex** [comment]
Ahí va! Falta instalar un certificado SSL en el servidor. Esto es necesario en nuestro módulo porque, al igual que todos los medios de pago, realizamos peticiones al servicio usando https, para que los datos estén siempre seguros.

Para realizar el checkout alcanza con utilizar un certificado gratuito, incluso si es autofirmado, pero si necesitás recibir la notificación con los datos del pago en el sitio vas a tener que utilizar una URL accesible públicamente con un certificado firmado por una entidad externa.
