### ISSUE TITLE
Incompatibilidad PrestaShop 8.1

### ISSUE THREAD

**Issue by ecommcodeshare** [mobbexco/prestashop#214]
Buenos días. Estamos instalando el módulo en P.8.1.0 y nos devuelve el siguiente error. Nos podrían ayudar con esto. Gracias
![error2](https://github.com/mobbexco/prestashop/assets/51239457/0751f7ee-ff80-4ab0-b5c8-1821f8dff372)
![error1](https://github.com/mobbexco/prestashop/assets/51239457/beb6adc2-5810-471c-8519-3390a2295368)

**Comment by jlmobbex** [comment]
Hola @ecommcodeshare! Gracias por tus comentarios, te comento que estamos trabajando activamente para traer compatibilidad a la versión 8.1 de PrestaShop, así que toda información que puedas brindarnos sobre estos errores (versión de PHP, registros o logs completos, etc) nos sería de mucha ayuda. Gracias!

**Comment by ecommcodeshare** [comment]
Estamos trabajando con la versión de php 7.3

**Comment by EMunozMobbex** [comment]
Hola @ecommcodeshare! Estuvimos revisando detalladamente el problema reportado en esta issue, el mismo pareciera corresponderse a una incorrecta instalación del plugin, utilizándose una build incompleta del mismo, recomendamos revisar atentamente el proceso de instalación descrito en el [readme](https://github.com/mobbexco/prestashop#instalaci%C3%B3n) con especial atención en descargar el plugin desde el enlace correcto, esperamos cualquier novedad que nos puedan comunicar después de probar una correcta instalación. Muchas gracias!

**Comment by jlmobbex** [comment]
Hola! Cierro esta issue por inactividad, y dejo una comentario que podría ayudar a evitar algunos errores:

PrestaShop [recomienda utilizar la versión 8.1 de PHP](https://devdocs.prestashop-project.org/8/basics/installation/system-requirements/) en las versiones superiores a PrestaShop 8. Se tiene conocimiento de varios bugs que afectan las funciones del panel de administración cuando se utilizan versiones inferiores.
